config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/rank' => 'ranks#index'
  get '/fan_rank' => 'fan_ranks#index'
  get '/team_rank' => 'team_ranks#index'
  get 'contact' => 'contacts#index'
  post 'contact/thanks' => 'contacts#thanks'
  get 'contact/done' => 'contacts#done'
  get '/room' => 'rooms#show'
  get '/play' => 'plays#play'
  get '/term' => 'terms#term'
  get '/privacy' => 'terms#privacy'
  resources :users
  resource :profile, only: %i[show edit update]
  resources :games do
    resources :expects, only: %i[new create show edit update]
  end
  resources :expects, only: %i[index]
  resources :messages, only: :create
  get '/show_additionally', to: 'rooms#show_additionally'
  mount ActionCable.server => '/cable'
end

app/controllers/team_ranks_controller.rb
# frozen_string_literal: true

class TeamRanksController < ApplicationController
  skip_before_action :require_login
  def index
    @giants = User.giants.all.sum(:point)
    @tigers = User.tigers.all.sum(:point)
    @dragons = User.dragons.all.sum(:point)
    @baystars = User.baystars.all.sum(:point)
    @carp = User.carp.all.sum(:point)
    @swallows = User.swallows.all.sum(:point)
    @hawks = User.hawks.all.sum(:point)
    @marines = User.marines.all.sum(:point)
    @lions = User.lions.all.sum(:point)
    @orix = User.orix.all.sum(:point)
    @fighters = User.fighters.all.sum(:point)
    @eagles = User.eagles.all.sum(:point)
  end
end

app/views/team_ranks/index.html.erb
<% content_for(:title, '球団別ポイント表') %>
<div class="rank">
<h1><%= "球団別ポイント表" %></h1>
</div>
<font color="white">
<%= link_to '球団内順位', fan_rank_path, class: "btn btn-flat team-rank" %>
<%= link_to '個人順位', rank_path, class: "btn btn-flat1 fan-rank"%>
</font>
    <table border="3" width="100" height="500">
    <h2 class="central"> セリーグ </h2>
         <tr>
        <th><div class="t1 text-center"><font color ="#F97709">読売ジャイアンツ</font></div></th>
           <td><div class="t1 text-center"><font color ="#F97709"><%= @giants %>p</font></td>
        </div>
       </tr>
       <tr>
         <th><div class="t1 text-center"><font color ="#ffe201">阪神タイガース</div></th></font>
         <td><div class="t1 text-center"><font color ="#ffe201"><%= @tigers %>p</font></div></td>
         </tr>
        <tr>
         <th><div class="t2 text-center"><font color ="#FFFFFF">中日ドラゴンズ</font></div></th>
         <td><div class="t2 text-center"><font color ="#FFFFFF"><%= @dragons %>p</div></td>
         </tr>
       <tr>
         <th><div class="t5 text-center"><font color ="ED1A3D">ヤクルトスワローズ</font></th>
         <td><div class="t5 text-center"><font color ="#ED1A3D"><%= @swallows %>p</font></td>
         </tr>
        
         
        <tr>
         <th><div class="t4 text-center"><font color ="#FFFFFF"><%= "広島カープ" %></font></th>
         <td><div class="t4 text-center"><font color ="#FFFFFF"><%= @carp %>p</div></font></td>
         </tr>
         <tr>
         <th><div class="t3 text-center"><font color ="#FFFFFF"><%= "DeNAベイスターズ" %></font></div></th>
         <td><div class="t3 text-center"><font color ="#FFFFFF"><%= @baystars %>p</td></div>
       </tr>
       </table>
         </div>

         <table border="3" width="100" height="500" >
         <h2 class="pacific"> パリーグ </h2>
         <tr>
         <th><div class="t1 text-center"><font color ="#f9ca00">ソフトバンクホークス</font></div></th>
           <td><div class="t1 text-center"><font color ="#f9ca00"><%= @hawks %>p</font></div></td>
           </tr>
           <tr>
         <th><div class="t1 text-center"><font color ="#FFFFFF">千葉ロッテマリーンズ</font></th>
         <td><div class="t1 text-center"><font color ="#FFFFFF"><%= @marines %>p</font></td>
         </tr>
         <tr>
         <th><div class="t7 text-center"><font color ="#FFFFFF">西武ライオンズ</font></th>
         <td><div class="t7 text-center"><font color ="#FFFFFF"><%= @lions %>p</font></td>
         </tr>
       <tr>
         <th><div class="t1 text-center"><font color ="#b08f32">オリックスバッファローズ</font></div></th>
         <td><div class="t1 text-center"><font color ="#b08f32"><%= @orix %>p</font></td>
         </tr>
         <tr>
         <th><div class="t9 text-center"><font color ="#e1a823">日本ハムファイターズ</font></th>
         <td><div class="t9 text-center"><font color ="#e1a823"><%= @fighters %>p</font></td>
         </tr>
         <tr>
         <th><div class="t8 text-center"><font color ="#FFFFFF">楽天ゴールデンイーグルス</font></div></th>
         <td><div class="t8 text-center"><font color ="#FFFFFF"><%= @eagles %>p</font></div></td>
         </tr>
         </div>
         </table>
         <div class="rank">
         </div>