config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/rank' => 'ranks#index'
  get '/fan_rank' => 'fan_ranks#index'
  get '/team_rank' => 'team_ranks#index'
  get 'contact' => 'contacts#index'
  post 'contact/thanks' => 'contacts#thanks'
  get 'contact/done' => 'contacts#done'
  get '/room' => 'rooms#show'
  get '/play' => 'plays#play'
  get '/term' => 'terms#term'
  get '/privacy' => 'terms#privacy'
  resources :users
  resource :profile, only: %i[show edit update]
  resources :games do
    resources :expects, only: %i[new create show edit update]
  end
  resources :expects, only: %i[index]
  resources :messages, only: :create
  get '/show_additionally', to: 'rooms#show_additionally'
  mount ActionCable.server => '/cable'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :expects
  has_many :messages, dependent: :destroy
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  mount_uploader :avatar, AvatarUploader

  enum favorite_team: { giants: 0, tigers: 1, dragons: 2,
                        baystars: 3, carp: 4, swallows: 5,
                        hawks: 6, marines: 7, lions: 8,
                        orix: 9, fighters: 10, eagles: 11 }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create index]
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to profile_path, success: 'ユーザーを作成しました'
    else
      render :new
      flash.now[:alert] = 'ユーザー作成に失敗しました'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def search_params
    params.require(:q).permit(:favorite_team_eq)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/_search.html.erb
<%= search_form_for(@q) do |f| %>
  <div class="cp_ipselect2 cp_sl03" %>
  <div class='input-group mb-3'>
  <%= f.select :favorite_team_eq,  options_for_select({'読売ジャイアンツ': 0, '阪神タイガース': 1, '中日ドラゴンズ': 2,'DeNAベイスターズ': 3, '広島カープ': 4, 'ヤクルトスワローズ': 5,'ソフトバンクホークス': 6, '千葉ロッテマリーンズ': 7,'西武ライオンズ': 8, 'オリックスバッファローズ': 9, '日本ハムファイターズ': 10, '楽天ゴールデンイーグルス': 11}),include_blank: '球団検索' %>
  </div>
  </div>
    <div class='search'>
    <%= f.submit value: "検索", class: "cp_button13" %>
  </div>
  <% end %>

app/views/users/index.html.erb
<% content_for(:title, 'ユーザー一覧') %>
<div class="ichiran" >
<h1>ユーザー一覧</h1>
</div>
<%= render 'search' %>
<div class="margin">
<table class="table table-condensed"> 
    <thead>
    <tr>
    <th scope="col">ユーザーネーム</th>
    <th scope="col">球団</th>
    <th scope="col">一言</th>
  </tr>
</thead>
<tbody>
<thead>
    <tr>
    <% @users.each do |user| %>
        <% if user.avatar? %>
        <td><%= image_tag user.avatar.url,
                      class: 'rounded-circle',
                      id: 'preview',
                      size: '30x30' %>  
        <% else %>
       <td> <%= image_tag asset_path('player.jpg'), :size => '30x30' %>
        <% end %>
        <%= link_to  user.name  ,user_path(user) %></td>
        <td><%= user.favorite_team_i18n %></td>
        <td><%= user.introduction %></td>
      </tr>
    <% end %>
  </tbody>
  <div class="pagenate">
</table>
<%= paginate @users %>
</div>
</div>

app/views/users/new.html.erb
<% content_for(:title, '新規登録') %>
<div id="login">
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-9">
                    <div id="login-box" class="col-md-12">
                    <div class="direction">
     <h1 class="text-center">新規登録</h1>
     <%= form_with model:@user, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  
  </div>
  <div class="actions">
  <%= f.submit "登録", class: "cp_button13" %>
  </div>
<% end %>
<div class='text-center'>
        <%= link_to "ログイン", login_path %>
   </div>
  </div>
 </div>
</div>
</div>
<div class="text-right">
<span class="ball"></span>
<span class="shadow"></span>
</div>
<div class="tate">
</div>

app/views/users/show.html.erb
<% content_for(:title, 'ユーザー詳細') %>
<div class="container pt-3">
<div class="row">
  <div class="col-md-10 offset-md-1">
    <h1 class="mypage"><%= "ユーザー詳細" %></h1>
       <table class="table text-center">
         <tr>
         <th scope="row"><%= "ユーザーネーム" %></th>
           <td><%= @user.name %></td>
         </tr>
        
         <tr>
         <th scope="row"><%= "球団" %></th>
         <td><%= @user.favorite_team_i18n %></td>
         </tr>
         <th scope="row"><%= "所持ポイント" %></th>
         <td><%= @user.point %></td>
         <tr>
          <th scope="row">アバター</th>
          <% if @user.avatar.present? %>
          <td><%= image_tag @user.avatar.url, class: 'rounded-circle mr15', width: '40px', height: '40px' %></td>

         <% else %>
            <td><%= image_tag 'player.jpg', class: 'rounded-circle mr15', width: '40px', height: '40px' %></td>
         <% end %>

        </tr>
         <tr>
         <th scope="row"><%= "一言" %></th>
         <td><%=  @user.introduction %></td>
         </tr>
       </table>
       <% if @user.id == current_user.id %>
       <%= link_to 'Edit', edit_profile_path(@user) %> |
       <% end %>
       <%= link_to 'Back', users_path %>
       </div>
     </div>
     </div>
     </div>
     <div class="tate">
     </div>