config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/rank' => 'ranks#index'
  get '/fan_rank' => 'fan_ranks#index'
  get '/team_rank' => 'team_ranks#index'
  get 'contact' => 'contacts#index'
  post 'contact/thanks' => 'contacts#thanks'
  get 'contact/done' => 'contacts#done'
  get '/room' => 'rooms#show'
  get '/play' => 'plays#play'
  get '/term' => 'terms#term'
  get '/privacy' => 'terms#privacy'
  resources :users
  resource :profile, only: %i[show edit update]
  resources :games do
    resources :expects, only: %i[new create show edit update]
  end
  resources :expects, only: %i[index]
  resources :messages, only: :create
  get '/show_additionally', to: 'rooms#show_additionally'
  mount ActionCable.server => '/cable'
end

app/views/shared/_before_login_header.html.erb
<header>
    <div class="bar">
      <%= link_to image_tag("logo.jpg", class:"logo_image"), root_path %>
			</div>
  </header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
  <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <ul>
    <li><%= link_to '遊び方', play_path %></li>
    <li><%= link_to '利用規約',term_path %></li>
    <li><%= link_to 'プライバシーポリシー', privacy_path %></li>
    <li><%= link_to 'お問い合わせ',contact_path %></li>
  </ul>
</div>

app/views/shared/_header.html.erb
<header>
<div class="bar">
<%= link_to image_tag("logo4.jpg", class:"logo_image"), root_path %>
</div>
<div class="header-menu1">
<%= link_to '試合一覧' ,games_path, class: "cp_btn1" %>
</div>
<div class="header-menu2">
<%= link_to '順位',rank_path, class: "cp_btn1" %>
</div>

<div class="cp_fullscreenmenu">
<input type="checkbox" id="menuToggle" />

<label for="menuToggle" class="hamburger">
<div class="open"></div>
</label>

<div class="menu menuEffects">
<label for="menuToggle"></label>
<div class="menucont">
<ul>
  <li><%= link_to '試合一覧',games_path %></li>
  <li><%= link_to '順位',rank_path %></li>
	<li><%= link_to '予想一覧',expects_path %></li>
  <li><%= link_to 'ユーザー一覧' ,users_path %></li>
	<li><%= link_to 'マイページ',profile_path %></li>	
	<li><%= link_to '遊び方',play_path %></li>
	<li><%= link_to 'ログアウト', logout_path,  method: :delete %></li>
</ul>
</div>
</div>
</div>
  </header>
	