config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/rank' => 'ranks#index'
  get '/fan_rank' => 'fan_ranks#index'
  get '/team_rank' => 'team_ranks#index'
  get 'contact' => 'contacts#index'
  post 'contact/thanks' => 'contacts#thanks'
  get 'contact/done' => 'contacts#done'
  get '/room' => 'rooms#show'
  get '/play' => 'plays#play'
  get '/term' => 'terms#term'
  get '/privacy' => 'terms#privacy'
  resources :users
  resource :profile, only: %i[show edit update]
  resources :games do
    resources :expects, only: %i[new create show edit update]
  end
  resources :expects, only: %i[index]
  resources :messages, only: :create
  get '/show_additionally', to: 'rooms#show_additionally'
  mount ActionCable.server => '/cable'
end

app/controllers/fan_ranks_controller.rb
# frozen_string_literal: true

class FanRanksController < ApplicationController
  skip_before_action :require_login
  def index
    user = current_user.favorite_team
    case user
    when 'giants'
      @user = User.giants.order(point: 'DESC')
    when 'tigers'
      @user = User.tigers.order(point: 'DESC')
    when 'dragons'
      @user = User.dragons.order(point: 'DESC')
    when 'carp'
      @user = User.carp.order(point: 'DESC')
    when 'baystars'
      @user = User.baystars.order(point: 'DESC')
    when 'swallows'
      @user = User.swallows.order(point: 'DESC')
    when 'hawks'
      @user = User.hawks.order(point: 'DESC')
    when 'marines'
      @user = User.marines.order(point: 'DESC')
    when 'lions'
      @user = User.lions.order(point: 'DESC')
    when 'orix'
      @user = User.orix.order(point: 'DESC')
    when 'fighters'
      @user = User.fighters.order(point: 'DESC')
    when 'eagles'
      @user = User.eagles.order(point: 'DESC')
    end
  end
end

app/views/fan_ranks/index.html.erb
<% content_for(:title, 'ファンランキング') %>
<div class="rank">
  <h1><%= current_user.favorite_team_i18n %>ファンランキング</h1>
  </div>
  <font color="white">
  <%= link_to '球団別ポイント表',team_rank_path,class: "btn btn-flat1 team-rank1" %>
  <%= link_to '個人順位',rank_path ,class: "btn btn-flat fan-rank1" %>
  </font>
  <table class="table-condensed" > 
      <thead>
      <tr>
      <th scope="col">順位</th>
      <th scope="col">ユーザーネーム</th>
      <th scope="col">ポイント数</th>
    </tr>
  </thead>
  <tbody>
  <thead>
      <tr>
      <% @user.each.with_index(1) do |r,i| %>
        <td>  第 <%= i %> 位 </td>
        <td><%= r.name %></td>
        <td><%= r.point %></td>
        </tr>
        <% end %>
        </thead>
     </tbody>
    </table>
    </style>
<div class="rank">
</div>